import { useEffect, useState } from 'react'
import { messageOf } from '../../../lib/apiClient'
import { evaluateAnswer, generateQuestion, getInterviewHistory } from '../api/interviewApi'
import { AppFrame } from '../../../layouts/DashboardLayout'
import { Button, Field, Notice, EmptyCard, Bullets } from '../../../components/ui'

export function MockInterview() {
 const [role,setRole]=useState(''),[difficulty,setDifficulty]=useState('Medium'),[question,setQuestion]=useState(''),[answer,setAnswer]=useState(''),[feedback,setFeedback]=useState(null),[history,setHistory]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const loadHistory=()=>getInterviewHistory().then(({data})=>setHistory(data.interviews||[])).catch(()=>{})
 useEffect(()=>{loadHistory()},[])
 const ask=async()=>{if(!role.trim())return setError('Add the role you’re practicing for.');setBusy(true);setError('');setFeedback(null);setAnswer('');try{const {data}=await generateQuestion({role,difficulty});setQuestion(data.question)}catch(e){setError(messageOf(e))}finally{setBusy(false)}}
 const evaluate=async e=>{e.preventDefault();if(!answer.trim())return setError('Write your answer before requesting feedback.');setBusy(true);setError('');try{const {data}=await evaluateAnswer({role,difficulty,question,answer});setFeedback(data.feedback);loadHistory()}catch(e){setError(messageOf(e))}finally{setBusy(false)}}
 return <AppFrame title="Mock interview" description="Practice in a low-pressure space. Each answer is a chance to learn."><div className="interview-layout"><section className="panel interview-main"><div className="panel-title"><div><span className="eyebrow">PRACTICE SESSION</span><h3>Let’s get you interview-ready</h3></div><span className="round-icon">◇</span></div><div className="form-grid interview-config"><Field label="Target role"><input value={role} onChange={e=>setRole(e.target.value)} placeholder="e.g. Frontend developer"/></Field><Field label="Difficulty"><select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option>Easy</option><option>Medium</option><option>Hard</option></select></Field></div><Button onClick={ask} busy={busy}>Generate a question ✳</Button>{error&&<Notice type="error">{error}</Notice>}{question&&<div className="question-card"><span className="eyebrow">YOUR QUESTION · {difficulty.toUpperCase()}</span><h3>{question}</h3><form onSubmit={evaluate}><Field label="Your answer" hint="Take a moment to structure your thoughts. There’s no timer."><textarea rows="7" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Type your answer here…"/></Field><Button type="submit" busy={busy} disabled={!answer.trim()}>Get feedback on my answer →</Button></form></div>}{feedback&&<FeedbackCard feedback={feedback}/>}</section><aside className="panel interview-aside"><span className="eyebrow">A LITTLE PRACTICE GOES FAR</span><div className="aside-stat"><strong>{history.length}</strong><span>sessions practiced</span></div><p>Pick a role, answer honestly, and use the feedback to keep improving.</p><div className="practice-tip"><span>✦</span><div><b>Try the STAR method</b><p>Set the scene, explain your task, describe your actions, then share the result.</p></div></div></aside></div><section className="panel history-panel"><div className="panel-title"><div><span className="eyebrow">YOUR PRACTICE LOG</span><h3>Recent interview sessions</h3></div><span className="history-count">{history.length} total</span></div>{history.length?<div className="history-list">{history.slice(0,6).map((item,i)=><div className="history-row" key={item._id||i}><span className="history-icon">◇</span><div className="history-info"><strong>{item.role}</strong><p>{item.question}</p><small>{new Date(item.createdAt).toLocaleDateString()} · {item.difficulty}</small></div><div className="score-badge">{item.score}<small>/100</small></div></div>)}</div>:<EmptyCard title="No interview attempts yet" text="Start a mock interview to see your attempts and feedback here."/>}</section></AppFrame>
}
export function FeedbackCard({feedback:f}) { return <div className="feedback-card"><div className="feedback-score"><div className="score-bubble">{f.score}<small>/100</small></div><div><span className="eyebrow">ANSWER EVALUATED</span><h3>Good work showing up.</h3><p>{f.communicationFeedback}</p></div></div><div className="feedback-grid"><div><h4>What worked well</h4><Bullets items={f.strengths}/></div><div><h4>What to improve</h4><Bullets items={f.areasToImprove}/></div></div>{f.betterAnswer&&<div className="better-answer"><h4>A stronger version to consider</h4><p>{f.betterAnswer}</p></div>}</div> }
