import { useState } from 'react'
import { messageOf } from '../../../lib/apiClient'
import { reviewResume } from '../api/resumeApi'
import { AppFrame } from '../../../layouts/DashboardLayout'
import { Button, Field, Notice, ResultSection, Bullets, Chips } from '../../../components/ui'

export function ResumeReview() {
 const [file,setFile]=useState(null),[text,setText]=useState(''),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const submit=async e=>{e.preventDefault();if(!file&&!text.trim())return setError('Upload a PDF or DOCX, or paste your resume text.');setBusy(true);setError('');setResult(null);try{const body=new FormData();if(file)body.append('resume',file);else body.append('resumeText',text);const {data}=await reviewResume(body);setResult(data.result)}catch(e){setError(messageOf(e))}finally{setBusy(false)}}
 const choose=e=>{const f=e.target.files?.[0];if(f&&(f.size>5*1024*1024||!(/\.pdf$/i.test(f.name)||/\.docx$/i.test(f.name)))){setError('Choose a PDF or DOCX file up to 5 MB.');e.target.value='';return}setError('');setFile(f||null)}
 return <AppFrame title="Resume review" description="Get thoughtful, specific feedback to make your experience easier to see."><div className="two-col-layout"><section className="panel form-panel"><div className="panel-title"><div><span className="eyebrow">A FRESH PERSPECTIVE</span><h3>Share your resume</h3></div><span className="round-icon">▤</span></div><form onSubmit={submit}><label className="upload-zone"><input type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={choose}/><span className="upload-icon">↑</span><strong>{file?file.name:'Choose a resume to upload'}</strong><span>{file?`${(file.size/1024/1024).toFixed(2)} MB · Ready to review`:'PDF or DOCX · Up to 5 MB'}</span><u>Browse files</u></label><div className="or-divider"><span>OR PASTE YOUR RESUME</span></div><Field label="Resume text"><textarea rows="9" value={text} onChange={e=>{setText(e.target.value);if(e.target.value) setFile(null)}} placeholder="Paste the text of your resume here…"/></Field>{error&&<Notice type="error">{error}</Notice>}<Button type="submit" busy={busy}>✳ &nbsp;Review my resume</Button></form><p className="privacy-note">Your resume is sent securely to the backend for analysis.</p></section>{result?<ResumeResults result={result}/>:<div className="empty-state"><div className="empty-illustration">▤<span>✦</span></div><h3>Make your experience stand out</h3><p>Get feedback on clarity, keywords, formatting, and ways to strengthen your story.</p></div>}</div></AppFrame>
}
export function ResumeResults({result:r}) { return <section className="panel result-panel"><div className="panel-title"><div><span className="eyebrow">YOUR RESUME REVIEW</span><h3>Suggestions to strengthen your story</h3></div><span className="status-pill"><i/> Complete</span></div><ResultSection title="Overall advice"><Bullets items={r.overallAdvice}/></ResultSection><ResultSection title="Areas to improve"><Bullets items={r.weaknesses}/></ResultSection><ResultSection title="ATS keywords"><Chips items={r.atsKeywords} tone="blue"/></ResultSection><ResultSection title="Formatting suggestions"><Bullets items={r.formattingSuggestions}/></ResultSection><ResultSection title="Skills to highlight"><Bullets items={r.skillsSuggestions}/></ResultSection><ResultSection title="Project suggestions"><Bullets items={r.projectSuggestions}/></ResultSection><ResultSection title="Experience suggestions"><Bullets items={r.experienceSuggestions}/></ResultSection><ResultSection title="Suggested summary"><p className="suggestion-text">{r.summarySuggestion||'No summary suggestion available.'}</p></ResultSection></section> }
