import { useState } from 'react'
import { Link } from 'react-router-dom'
import { messageOf, list } from '../../../lib/apiClient'
import { getCareerGuidance } from '../api/careerGuidanceApi'
import { AppFrame } from '../../../layouts/DashboardLayout'
import { Button, Notice, ResultSection, Chips } from '../../../components/ui'

export function CareerGuidance() {
 const [guidance,setGuidance]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const generate=async()=>{setBusy(true);setError('');try{const {data}=await getCareerGuidance();setGuidance(data.guidance)}catch(e){setError(messageOf(e))}finally{setBusy(false)}}
 return <AppFrame title="Career paths" description="Explore possibilities shaped by what you know, enjoy, and want next." action={<Button busy={busy} onClick={generate}>✳ &nbsp;{guidance?'Refresh guidance':'Get my guidance'}</Button>}>{error&&<Notice type="error">{error}</Notice>}{guidance?<><section className="career-intro panel"><span className="round-icon">✳</span><div><span className="eyebrow">A PERSONALIZED STARTING POINT</span><h3>Paths worth exploring</h3><p>{guidance.overallAdvice}</p></div></section><div className="career-grid">{list(guidance.recommendedCareers).map((c,i)=><article className="panel career-card" key={i}><div className="career-card-head"><span className="step-num">0{i+1}</span><span className="career-match">{c.matchPercentage}%<small> profile match</small></span></div><h3>{c.career}</h3><p>{c.reason}</p><div className="match-bar"><span style={{width:`${Math.min(100,Math.max(0,Number(c.matchPercentage)||0))}%`}}/></div><ResultSection title="Skills to bring"><Chips items={c.requiredSkills} tone="blue"/></ResultSection><ResultSection title="Skills to develop"><Chips items={c.skillsToImprove} tone="orange"/></ResultSection><Link to="/learning-roadmap" className="text-link" onClick={()=>localStorage.setItem('career_missing',JSON.stringify(list(c.skillsToImprove)))}>Build a learning plan →</Link></article>)}</div>{list(guidance.nextSteps).length>0&&<section className="panel next-steps-panel"><span className="eyebrow">A FEW WAYS TO BEGIN</span><h3>Your next steps</h3><ol>{guidance.nextSteps.map((s,i)=><li key={i}><span>{String(i+1).padStart(2,'0')}</span>{s}</li>)}</ol></section>}</>:<div className="guidance-empty panel"><div className="empty-illustration">✳<span>✦</span></div><h3>Let’s find your direction</h3><p>We’ll use the skills, projects, and interests in your profile to suggest career paths worth exploring.</p><Link className="text-link" to="/profile">Review your profile first ↗</Link><div><Button busy={busy} onClick={generate}>Get personalized guidance →</Button></div></div>}</AppFrame>
}
