import { useState } from 'react'
import { messageOf, list } from '../../../lib/apiClient'
import { recommendResources } from '../api/resourcesApi'
import { AppFrame } from '../../../layouts/DashboardLayout'
import { Button, Notice, EmptyCard } from '../../../components/ui'

export function Resources() {
 const [skills,setSkills]=useState(()=>JSON.parse(localStorage.getItem('career_missing')||'[]')),[manual,setManual]=useState(''),[resources,setResources]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const search=async()=>{if(!skills.length)return setError('Add at least one skill to find resources.');setBusy(true);setError('');try{const {data}=await recommendResources(skills);setResources(data.resources||[])}catch(e){setError(messageOf(e))}finally{setBusy(false)}}
 const add=()=>{const next=manual.split(',').map(s=>s.trim()).filter(s=>s&&!skills.includes(s));setSkills([...skills,...next]);setManual('')}
 return <AppFrame title="Learning resources" description="Find a mix of explanations, videos, and places to practice."><section className="panel roadmap-input"><div className="panel-title"><div><span className="eyebrow">LEARN BY DOING</span><h3>Pick a skill to explore</h3></div><span className="round-icon">↗</span></div><div className="chips roadmap-chips">{skills.map((x,i)=><span className="chip blue" key={i}>{x}<button aria-label={`Remove ${x}`} onClick={()=>setSkills(skills.filter((_,j)=>j!==i))}>×</button></span>)}</div><div className="inline-add"><input value={manual} onChange={e=>setManual(e.target.value)} onKeyDown={e=>e.key==='Enter'&&(e.preventDefault(),add())} placeholder="Add skills, separated by commas"/><Button variant="secondary" onClick={add}>Add skills</Button><Button busy={busy} onClick={search} disabled={!skills.length}>Find resources →</Button></div>{error&&<Notice type="error">{error}</Notice>}</section>{resources&&<div className="resource-list">{resources.length?resources.map((resource,i)=><ResourceCard resource={resource} key={`${resource.skill}-${i}`}/>):<EmptyCard title="No resources found" text="Try again with another skill."/>}</div>}</AppFrame>
}
export function ResourceCard({resource}) { const [tab,setTab]=useState('Notes');const tabs=['Notes','Videos','Channels','Practice'];const counts=[list(resource.notes).length,list(resource.videos).length,list(resource.channels).length,list(resource.practiceWebsites).length];return <section className="panel resource-card"><div className="panel-title"><div><span className="eyebrow">LEARNING COLLECTION</span><h3>{resource.skill}</h3></div><span className="round-icon">✦</span></div><div className="tabs" role="tablist" aria-label={`${resource.skill} resources`}>{tabs.map((x,i)=><button role="tab" aria-selected={tab===x} className={tab===x?'selected':''} key={x} onClick={()=>setTab(x)}>{x}<span>{counts[i]}</span></button>)}</div>{tab==='Notes'&&(counts[0]?<div className="notes-grid">{resource.notes.map((n,i)=><article className="note-card" key={i}><h4>{n.topic}</h4><p>{n.explanation}</p>{list(n.importantPoints).length>0&&<ul className="clean-list">{n.importantPoints.map((p,j)=><li key={j}>{p}</li>)}</ul>}</article>)}</div>:<EmptyCard title="No notes available yet" text="There are no generated notes for this skill."/>)}{tab==='Videos'&&(counts[1]?<div className="media-grid">{resource.videos.map((v,i)=><a className="media-card" key={i} href={v.url} target="_blank" rel="noopener noreferrer">{v.thumbnail&&<img src={v.thumbnail} alt="" loading="lazy"/>}<div><small>{v.channelTitle}</small><h4>{v.title}</h4><span className="text-link">Watch video ↗</span></div></a>)}</div>:<EmptyCard title="No videos found" text="No videos are available for this skill right now."/>)}{tab==='Channels'&&(counts[2]?<div className="media-grid">{resource.channels.map((c,i)=><a className="channel-card" key={i} href={c.url} target="_blank" rel="noopener noreferrer">{c.thumbnail&&<img src={c.thumbnail} alt="" loading="lazy"/>}<div><h4>{c.channelTitle}</h4><p>{c.description}</p><span className="text-link">Visit channel ↗</span></div></a>)}</div>:<EmptyCard title="No channels found" text="No channels are available for this skill right now."/>)}{tab==='Practice'&&(counts[3]?<div className="practice-links">{resource.practiceWebsites.map((s,i)=><a key={i} href={s.url} target="_blank" rel="noopener noreferrer"><span className="practice-mark">↗</span><span><b>{s.name}</b><small>Practice {resource.skill}</small></span><span className="link-arrow">↗</span></a>)}</div>:<EmptyCard title="No practice sites found" text="No practice websites are available for this skill yet."/>)}</section>}
