import { useEffect, useState } from 'react'
import { messageOf, list } from '../../../lib/apiClient'
import { getProfile, updateProfile } from '../api/profileApi'
import { AppFrame } from '../../../layouts/DashboardLayout'
import { Button, Field, Notice } from '../../../components/ui'

export function Profile() {
 const [profile,setProfile]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('')
 useEffect(()=>{getProfile().then(({data})=>setProfile({...data,skills:list(data.skills),certifications:list(data.certifications),projects:list(data.projects),interests:list(data.interests),careerPreferences:list(data.careerPreferences)})).catch(e=>setError(messageOf(e)))},[])
 const update=(key,val)=>setProfile(p=>({...p,[key]:val}));const submit=async e=>{e.preventDefault();setBusy(true);setError('');setSuccess('');try{const {data}=await updateProfile(profile);setProfile({...data.user});setSuccess(data.message||'Profile updated successfully.')}catch(e){setError(messageOf(e))}finally{setBusy(false)}}
 if(!profile)return <AppFrame title="My profile" description="Tell us what you’ve learned and where you want to go.">{error?<Notice type="error">{error}</Notice>:<div className="loading-state">Loading your profile…</div>}</AppFrame>
 return <AppFrame title="My profile" description="Your experience helps us make your next steps more personal."><form className="profile-form" onSubmit={submit}><section className="panel profile-top-card"><span className="avatar xl">{(profile.name||'S').slice(0,1).toUpperCase()}</span><div><span className="eyebrow">YOUR CAREER PROFILE</span><h3>{profile.name}</h3><p>{profile.email}</p></div><span className="profile-tag">Private profile</span></section><section className="panel profile-section"><div className="profile-section-heading"><span className="section-number">01</span><div><h3>About you</h3><p>The basics that shape your recommendations.</p></div></div><div className="form-grid"><Field label="Full name"><input required value={profile.name||''} onChange={e=>update('name',e.target.value)} /></Field><Field label="Email address" hint="Email is managed by your account and cannot be changed here."><input type="email" disabled value={profile.email||''}/></Field><Field label="Education" hint="Your degree, program, or current studies." ><input value={profile.education||''} onChange={e=>update('education',e.target.value)} placeholder="e.g. BSc Computer Science, 2025"/></Field></div></section><section className="panel profile-section"><div className="profile-section-heading"><span className="section-number">02</span><div><h3>Your experience</h3><p>Capture the skills and work you’re proud of.</p></div></div><div className="form-grid"><TagField label="Skills" value={profile.skills} onChange={v=>update('skills',v)} placeholder="Add a skill and press Enter"/><TagField label="Certifications" value={profile.certifications} onChange={v=>update('certifications',v)} placeholder="e.g. AWS Cloud Practitioner"/><TagField label="Projects" value={profile.projects} onChange={v=>update('projects',v)} placeholder="e.g. Personal portfolio site"/></div></section><section className="panel profile-section"><div className="profile-section-heading"><span className="section-number">03</span><div><h3>What interests you?</h3><p>Help us understand what energizes you.</p></div></div><div className="form-grid"><TagField label="Interests" value={profile.interests} onChange={v=>update('interests',v)} placeholder="e.g. Building useful products"/><TagField label="Career preferences" value={profile.careerPreferences} onChange={v=>update('careerPreferences',v)} placeholder="e.g. Product design, Remote work"/></div></section>{error&&<Notice type="error">{error}</Notice>}{success&&<Notice>{success}</Notice>}<div className="form-actions"><span className="muted">Changes save to your account.</span><Button busy={busy} type="submit">Save profile changes →</Button></div></form></AppFrame>
}
export function TagField({label,value=[],onChange,placeholder}) { const [draft,setDraft]=useState('');const add=()=>{const v=draft.trim();if(v&&!value.includes(v))onChange([...value,v]);setDraft('')};return <Field label={label}><div className="tag-input"><div className="tag-list">{list(value).map((x,i)=><span className="tag" key={`${x}-${i}`}>{x}<button type="button" onClick={()=>onChange(value.filter((_,j)=>i!==j))} aria-label={`Remove ${x}`}>×</button></span>)}</div><div className="tag-entry"><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();add()}}} placeholder={placeholder}/><button type="button" onClick={add} aria-label={`Add ${label}`}>+</button></div></div></Field> }
