import { useState } from 'react'
import { messageOf } from '../../../lib/apiClient'
import { generateRoadmap } from '../api/roadmapApi'
import { AppFrame } from '../../../layouts/DashboardLayout'
import { Button, Notice, EmptyCard, Bullets } from '../../../components/ui'

export function Roadmap() {
 const [skills,setSkills]=useState(()=>JSON.parse(localStorage.getItem('career_missing')||'[]')),[manual,setManual]=useState(''),[roadmap,setRoadmap]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const generate=async values=>{if(!values.length)return setError('Add at least one skill to build your roadmap.');setBusy(true);setError('');try{const {data}=await generateRoadmap(values);setRoadmap(data.roadmap||[])}catch(e){setError(messageOf(e))}finally{setBusy(false)}}
 const add=()=>{const next=manual.split(',').map(s=>s.trim()).filter(s=>s&&!skills.includes(s));if(next.length){setSkills([...skills,...next]);setManual('')}}
 return <AppFrame title="Learning roadmap" description="A practical path forward, built around the skills you want to grow."><section className="panel roadmap-input"><div className="panel-title"><div><span className="eyebrow">YOUR LEARNING PLAN</span><h3>Which skills are you building?</h3></div><span className="round-icon">⌁</span></div><p className="muted">Start with skills from your analysis, or add your own.</p><div className="chips roadmap-chips">{skills.map((x,i)=><span className="chip blue" key={i}>{x}<button aria-label={`Remove ${x}`} onClick={()=>setSkills(skills.filter((_,j)=>j!==i))}>×</button></span>)}</div><div className="inline-add"><input value={manual} onChange={e=>setManual(e.target.value)} onKeyDown={e=>e.key==='Enter'&&(e.preventDefault(),add())} placeholder="Add skills, separated by commas"/><Button variant="secondary" onClick={add}>Add skills</Button><Button busy={busy} onClick={()=>generate(skills)} disabled={!skills.length}>✳ &nbsp;Build my roadmap</Button></div>{error&&<Notice type="error">{error}</Notice>}</section>{roadmap?<section className="roadmap-list"><div className="section-head"><div><span className="eyebrow">YOUR PERSONAL PLAN</span><h2>{roadmap.length} {roadmap.length===1?'skill':'skills'} to explore</h2></div><Button variant="secondary" onClick={()=>generate(skills)} busy={busy}>Refresh plan ↻</Button></div>{roadmap.length?roadmap.map((item,i)=><article className="panel roadmap-item" key={`${item.skill}-${i}`}><div className="roadmap-number">{String(i+1).padStart(2,'0')}</div><div className="roadmap-content"><div className="roadmap-title"><div><h3>{item.skill}</h3><p>{item.reason}</p></div><span className={`priority ${String(item.priority).toLowerCase()}`}>{item.priority} priority</span></div><div className="roadmap-meta"><span>◷ &nbsp;{item.estimatedTime||'Time varies'}</span></div><div className="roadmap-detail-grid"><div><h4>Topics to learn</h4><Bullets items={item.topics}/></div><div><h4>Practice projects</h4><Bullets items={item.practiceProjects}/></div></div></div></article>):<EmptyCard title="No roadmap items returned" text="Try generating a plan with another skill."/>}</section>:<div className="roadmap-empty"><div className="empty-illustration">⌁<span>✦</span></div><h3>A good plan makes the next step easier</h3><p>Add one or more skills above and we’ll organize them into a learning journey.</p></div>}</AppFrame>
}
