import { useState } from 'react'
import { messageOf } from '../../../lib/apiClient'
import { analyzeJobDescription } from '../api/jobAnalysisApi'
import { AppFrame } from '../../../layouts/DashboardLayout'
import { Button, Field, Notice, ResultSection, Chips, Bullets } from '../../../components/ui'

export function JobAnalyzer() {
 const [text,setText]=useState(''),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const submit=async e=>{e.preventDefault();if(!text.trim())return setError('Paste a job description to get started.');setBusy(true);setError('');setResult(null);try{const {data}=await analyzeJobDescription(text);setResult(data.result)}catch(e){setError(messageOf(e))}finally{setBusy(false)}}
 return <AppFrame title="Job description analyzer" description="Turn a long job post into a clear picture of what the role needs."><div className="two-col-layout"><section className="panel form-panel"><div className="panel-title"><div><span className="eyebrow">STEP 1 · ADD A ROLE</span><h3>Paste the job description</h3></div><span className="round-icon">⌕</span></div><form onSubmit={submit}><Field label="Job description" hint={`${text.trim().split(/\s+/).filter(Boolean).length} words · Include the full description for a better analysis`}><textarea rows="13" maxLength="20000" value={text} onChange={e=>setText(e.target.value)} placeholder="Paste the job description here. Include responsibilities, qualifications, and any skills listed…"/></Field>{error&&<Notice type="error">{error}</Notice>}<Button busy={busy} type="submit" disabled={!text.trim()}>✳ &nbsp;Analyze job description</Button></form><div className="privacy-note">✦ &nbsp;Your job description is only used for this analysis.</div></section><section className="result-column">{result?<JobResults result={result}/>:<div className="empty-state"><div className="empty-illustration">⌕<span>✦</span></div><h3>Your role breakdown will appear here</h3><p>We’ll organize the job post into skills, qualifications, and responsibilities you can act on.</p><div className="empty-points"><span>✓ &nbsp;Required and preferred skills</span><span>✓ &nbsp;Role and experience summary</span><span>✓ &nbsp;Key qualifications</span></div></div>}</section></div></AppFrame>
}
export function JobResults({result}) { return <div className="panel result-panel"><div className="panel-title"><div><span className="eyebrow">ROLE BREAKDOWN</span><h3>{result?.jobTitle||'Job description analysis'}</h3></div><span className="status-pill"><i/> Analyzed</span></div><div className="result-highlight"><span className="eyebrow">EXPERIENCE</span><strong>{result?.experience||'Not specified'}</strong></div><ResultSection title="Required skills"><Chips items={result?.requiredSkills} tone="blue"/></ResultSection><ResultSection title="Preferred skills"><Chips items={result?.preferredSkills} tone="lavender"/></ResultSection><ResultSection title="Qualifications"><Bullets items={result?.qualifications}/></ResultSection><ResultSection title="What you’ll do"><Bullets items={result?.responsibilities}/></ResultSection></div> }
