import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { messageOf, list } from '../../../lib/apiClient'
import { analyzeSkillGap } from '../api/skillGapApi'
import { AppFrame } from '../../../layouts/DashboardLayout'
import { Button, Field, Notice, ResultSection, Chips } from '../../../components/ui'

export function SkillGap() {
 const [text,setText]=useState(''),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const submit=async e=>{e.preventDefault();if(!text.trim())return setError('Paste a job description first.');setBusy(true);setError('');try{const {data}=await analyzeSkillGap(text);setResult(data)}catch(e){setError(messageOf(e))}finally{setBusy(false)}}
 return <AppFrame title="Skill gap analysis" description="See where your skills line up with a role, and what you could build next."><div className="two-col-layout"><section className="panel form-panel"><div className="panel-title"><div><span className="eyebrow">COMPARE YOUR SKILLS</span><h3>Choose a role to explore</h3></div><span className="round-icon">◎</span></div><form onSubmit={submit}><Field label="Job description" hint="We’ll compare this role against the skills on your profile."><textarea rows="12" value={text} onChange={e=>setText(e.target.value)} placeholder="Paste the full job description…"/></Field>{error&&<Notice type="error">{error}</Notice>}<Button busy={busy} type="submit" disabled={!text.trim()}>Analyze my skill fit →</Button></form><p className="privacy-note">Don’t have skills on your profile yet? <Link to="/profile">Add them first ↗</Link></p></section>{result?<GapResults result={result}/>:<div className="empty-state"><div className="empty-illustration">◎<span>✦</span></div><h3>Your skill map starts here</h3><p>Compare your profile with a role to discover strengths and opportunities.</p></div>}</div></AppFrame>
}
export function GapResults({result}) { const navigate=useNavigate();return <div className="result-column"><section className="panel match-panel"><div className="panel-title"><div><span className="eyebrow">YOUR SKILL FIT</span><h3>{result.job?.title||'Role match'}</h3></div><span className="round-icon">◎</span></div><div className="match-display"><div className="match-ring" style={{'--match':`${Number(result.matchPercentage)||0}%`}} role="img" aria-label={`${result.matchPercentage}% skill match`}><div><strong>{result.matchPercentage??0}<small>%</small></strong><span>skill match</span></div></div><p>This reflects required skills in this job description. It is not a prediction of hiring outcomes.</p></div><div className="match-bar-label"><span>Required skills covered</span><b>{result.matchPercentage??0}%</b></div><div className="match-bar" role="progressbar" aria-valuenow={Number(result.matchPercentage)||0} aria-valuemin="0" aria-valuemax="100"><span style={{width:`${Math.min(100,Math.max(0,Number(result.matchPercentage)||0))}%`}}/></div><div className="mini-stats"><div><span className="stat-dot green"/>{list(result.matchedSkills).length} matched</div><div><span className="stat-dot orange"/>{list(result.missingSkills).length} to explore</div></div></section><section className="panel result-panel gap-breakdown"><div className="panel-title"><div><span className="eyebrow">YOUR BREAKDOWN</span><h3>Where to focus</h3></div></div><ResultSection title="Matched skills"><Chips items={result.matchedSkills} tone="green"/></ResultSection><ResultSection title="Missing required skills"><Chips items={result.missingSkills} tone="orange"/></ResultSection><ResultSection title="Preferred skills"><Chips items={result.preferredSkills} tone="lavender"/></ResultSection><ResultSection title="Missing preferred skills"><Chips items={result.missingPreferredSkills} tone="orange"/></ResultSection>{list(result.missingSkills).length>0&&<div className="next-step-actions"><Button onClick={()=>{localStorage.setItem('career_missing',JSON.stringify(result.missingSkills));navigate('/learning-roadmap')}}>Create my learning roadmap →</Button><Button variant="secondary" onClick={()=>{localStorage.setItem('career_missing',JSON.stringify(result.missingSkills));navigate('/resources')}}>Find learning resources</Button></div>}</section></div> }
